### ISSUE TITLE
nntest module adjustments

### ISSUE THREAD

**Issue by Chunosov** [ctuning/ck-nntest#11]
- [x] Copy `libarm_compute_core.so` when switch to processing another new library instance, but not to copy when iterating over datasets and batch sizes for the same library (using `CK_PUSH_LIBS_TO_REMOTE`)
- [x] Enable `--record` by default and provide `--no-record` instead
- [x] mention `--dry_run` in the main `README`
- [x]  `--dry_run` should list all libraries, datasets and batch sizes that would be iterated over, print the repo name and tags, and the total number of experiments
- [x]  11 `*.json` files in `dataset/tensor-conv3x3-inception-v3` but 17 layers in `data.csv`; check for duplicates
- [x] CK_ENABLE_FAST_MATH should be 1 by default
- [x] do not fail benchmark on errors like `direct-conv only supports kernel=1,3,5 (you selected kernel=7)`, skip unsupported shapes
- [x] select gpu before benchmark and pass selection to all later commands (https://github.com/ctuning/ck-nntest/issues/11#issuecomment-409524114)
- [x] implement [`--resume`](https://github.com/ctuning/ck-nntest/issues/11#issuecomment-405126063)

**Comment by psyhtest** [comment]
Also, if we keep working with the same library and only vary datasets and batch sizes, there's no need to recompile and push the program?

**Comment by Chunosov** [comment]
I'm not sure if it possible, will check, but it may be part of underlying ck-operations (pipeline?)

**Comment by Chunosov** [comment]
> 11 *.json files in dataset/tensor-conv3x3-inception-v3 but 17 layers in data.csv; check for duplicates

Seems there is nothing to fix here. `data.csv` contains all 3x3 convolution layers of Inception-v3, just for completeness. But when we generate `json` files using `tool-prepare-dataset`, it skips all layers having duplicated set of parameters.

**Comment by psyhtest** [comment]
> But when we generate json files using tool-prepare-dataset, it skips all layers having duplicated set of parameters.
Cool.

**Comment by Chunosov** [comment]
Here is PR https://github.com/ctuning/ck-nntest/pull/14 that can help to implement remaining enhancements.

**Comment by Chunosov** [comment]
Considering GPU detection, use commands:
```
ii={'action':'detect',
        'module_uoa':'platform.gpgpu',
        'compute_platform_id':i.get('compute_platform_id',''),
        'compute_device_id':i.get('compute_device_id',''),
        'out':'con'}
    r=ck.access(ii)
    if r['return']>0: return r
    print (r['choices'])
```
> and you can also actually pass 'compute_platform_id' and 'compute_device_id' from command line of ck-nntest to let use force them even from the start, i.e.
> Also 'out':'out' should be 'out':'con'

**Comment by Chunosov** [comment]
>  do not fail benchmark on errors like direct-conv only supports kernel=1,3,5 (you selected kernel=7), skip unsupported shapes

This is not a problem with `nntest` module. It only occurs when run with `--ddvdv_prof`. Here is the fix for module `program`: https://github.com/ctuning/ck-autotuning/commit/abd3de187ceb9749320f1c131b5a636c13a151cd

**Comment by psyhtest** [comment]
Many thanks @Chunosov! I don't have any more suggestions at the moment (phew), so closing this issue.
