### ISSUE TITLE
Test with 'directconv-armcl-opencl' with 'NHWC' fails on 'tensor-conv-mobilenets-v1-0.75-160'

### ISSUE THREAD

**Issue by bellycat77** [ctuning/ck-nntest#24]
When I running test with command:
```
ck run nntest:directconv-armcl-opencl --repetitions=10 --iterations=1 \
  --library=$LIBRARY --dataset_uoa=tensor-conv-mobilenets-v1-0.75-160 \
  --env.CK_LWS_TUNER_TYPE=DEFAULT --env.CK_DATA_LAYOUT=NHWC \
  --timestamp=firefly-tensor-conv-mobilenets-v1-0.75-160-tuner-default-layout-nhwc-validation
```

It fails on 11th step, **second** iteration with error message `Pipeline failed (execution failed - output is not matching...`
Unmatching points are different between runs

But when we run validation just with `ck run program:directconv-armcl-opencl` all shapes of this dataset are validated correctly

The command:
```
ck run nntest:directconv-armcl-opencl --repetitions=10 --iterations=1 \
  --library=$LIBRARY --dataset_uoa=tensor-conv-mobilenets-v1-1.0-224 \
  --env.CK_LWS_TUNER_TYPE=DEFAULT --env.CK_DATA_LAYOUT=NHWC \
  --timestamp=firefly-tensor-conv-mobilenets-v1-1.0-224-tuner-default-layout-nhwc-validation
```
also has problems with data validation in some experiments.

**Comment by bellycat77** [comment]
The same command
```
ck run nntest:directconv-armcl-opencl --repetitions=10 --iterations=1 \
  --library=$LIBRARY --dataset_uoa=tensor-conv-mobilenets-v1-0.75-160 \
  --env.CK_LWS_TUNER_TYPE=DEFAULT --env.CK_DATA_LAYOUT=NHWC \
  --timestamp=firefly-tensor-conv-mobilenets-v1-0.75-160-tuner-default-layout-nhwc-validation
```
 on `hikey` finished without any errors

**Comment by psyhtest** [comment]
According to https://github.com/ARM-software/ComputeLibrary/issues/551, this has been fixed and will appear in the "next release". I've asked if they meant v18.11 or later.
