### ISSUE TITLE
Experiment for 'directconv-armcl-opencl' with 'NHWC' failed

### ISSUE THREAD

**Issue by bellycat77** [ctuning/ck-nntest#25]
With command:
```
$ ck run program:directconv-armcl-opencl \
--dataset_uoa=tensor-conv5x5-inception-v3 \
--env.CK_LWS_TUNER_TYPE=NONE \
--env.CK_DATA_LAYOUT=NHWC
```
error arises:
```
terminate called after throwing an instance of 'cl::Error'
        what():  clEnqueueMapBuffer
```
The same error arises with `--env.CK_LWS_TUNER_TYPE=DEFAULT`.

In some cases I got error `Pipeline failed (execution failed - output is not matching...` . No such errors when using other datasets.

**Comment by psyhtest** [comment]
Presumably, no errors with `--env.CK_DATA_LAYOUT=NCHW`?

**Comment by bellycat77** [comment]
> Presumably, no errors with `--env.CK_DATA_LAYOUT=NCHW`?

That's right. There are no any errors in case with `--env.CK_DATA_LAYOUT=NCHW`
